server:
  port: 8082

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/account_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Inter-service communication
customer-service:
  base-url: http://customer-service/api/customers
