server:
  port: 0

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Kafka event configuration
kafka:
  bootstrap-servers: localhost:9092
  topic:
    transactions: transaction-events
